services:
    ubuntu:
        public: true
        container_name: tzchz
        image: aank999/xrdp-okteto-cloud:latest
        ports:
            - 80:80
        volumes: 
            - /root/Desktop
            - /home
        resources:
          cpu: 2000m
          memory: 6000Mi
          storage:
            size: 2Gi
            class: ssd
